/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch01.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch02.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch03.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch04.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch05.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch06.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch07.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch08.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch09.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch10.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch11.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch12.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch13.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch14.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch15.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch16.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch17.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch18.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch19.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch20.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch21.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch22.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch23.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch24.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch25.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch26.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch27.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch28.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch29.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch30.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch31.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch32.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch33.do" & 
/usr/local/bin/stata-mp -b do "/Users/Israel/Dropbox/Data/DataMexico_MunicipalTrade/code/batch/batch33.do"   
